version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    env_file: .env
    volumes:
      - dbfile:/var/lib/mysql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      retries: 3
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend

  wp:
    image: wordpress:5.7.0-php8.0-fpm
    container_name: wordpress-5.7.0-php8.0-fpm
    depends_on:
      - mysql
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www-html:/var/www/html
    networks:
      - backend

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - wp
    container_name: nginx-1.19.8-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 2
    networks:
      - backend

volumes:
  www-html:
  dbfile:

networks:
  backend:
    driver: bridge